var data = {
	weapon_dates: [
		["高塔孤王", "孤云寒林"],
		["凛风奔狼", "雾海云间"],
		["狮牙斗士", "漆黑陨铁"],
		["高塔孤王", "孤云寒林"],
		["凛风奔狼", "雾海云间"],
		["狮牙斗士", "漆黑陨铁"],
	],
	char_dates: [
		["自由", "繁荣"],
		["抗争", "勤劳"],
		["诗文", "黄金"],
		["自由", "繁荣"],
		["抗争", "勤劳"],
		["诗文", "黄金"],
	],
	weapons: {
		高塔孤王: [
			{
				name: "风鹰剑",
				req: "高塔孤王",
				region: "蒙德",
				star: "5",
				req1: "号角",
				req2: "箭簇",
				type: "weapon",
			},
			{
				name: "西风剑",
				req: "高塔孤王",
				region: "蒙德",
				star: "4",
				req1: "号角",
				req2: "箭簇",
				type: "weapon",
			},
			{
				name: "钟剑",
				req: "高塔孤王",
				region: "蒙德",
				star: "4",
				req1: "号角",
				req2: "花蜜",
				type: "weapon",
			},
			{
				name: "宗室长剑",
				req: "高塔孤王",
				region: "蒙德",
				star: "4",
				req1: "号角",
				req2: "面具",
				type: "weapon",
			},
			{
				name: "雪葬的星银",
				req: "高塔孤王",
				region: "蒙德",
				star: "4",
				req1: "号角",
				req2: "史莱姆",
				type: "weapon",
			},
			{
				name: "绝弦",
				req: "高塔孤王",
				region: "蒙德",
				star: "4",
				req1: "号角",
				req2: "箭簇",
				type: "weapon",
			},
			{
				name: "苍翠猎弓",
				req: "高塔孤王",
				region: "蒙德",
				star: "4",
				req1: "号角",
				req2: "箭簇",
				type: "weapon",
			},
			{
				name: "宗室秘法录",
				req: "高塔孤王",
				region: "蒙德",
				star: "4",
				req1: "号角",
				req2: "徽记",
				type: "weapon",
			},
			{
				name: "西风秘典",
				req: "高塔孤王",
				region: "蒙德",
				star: "4",
				req1: "号角",
				req2: "绘卷",
				type: "weapon",
			},
		],
		凛风奔狼: [
			{
				name: "天空之刃",
				req: "凛风奔狼",
				region: "蒙德",
				star: "5",
				req1: "地脉",
				req2: "史莱姆",
				type: "weapon",
			},
			{
				name: "天空之傲",
				req: "凛风奔狼",
				region: "蒙德",
				star: "5",
				req1: "地脉",
				req2: "史莱姆",
				type: "weapon",
			},
			{
				name: "天空之翼",
				req: "凛风奔狼",
				region: "蒙德",
				star: "5",
				req1: "地脉",
				req2: "箭簇",
				type: "weapon",
			},
			{
				name: "天空之卷",
				req: "凛风奔狼",
				region: "蒙德",
				star: "5",
				req1: "地脉",
				req2: "箭簇",
				type: "weapon",
			},
			{
				name: "黑剑",
				req: "凛风奔狼",
				region: "蒙德",
				star: "4",
				req1: "地脉",
				req2: "史莱姆",
				type: "weapon",
			},
			{
				name: "笛剑",
				req: "凛风奔狼",
				region: "蒙德",
				star: "4",
				req1: "地脉",
				req2: "史莱姆",
				type: "weapon",
			},
			{
				name: "降临之剑",
				req: "凛风奔狼",
				region: "蒙德",
				star: "4",
				req1: "地脉",
				req2: "鸦印",
				type: "weapon",
			},
			{
				name: "祭礼大剑",
				req: "凛风奔狼",
				region: "蒙德",
				star: "4",
				req1: "地脉",
				req2: "箭簇",
				type: "weapon",
			},
			{
				name: "祭礼弓",
				req: "凛风奔狼",
				region: "蒙德",
				star: "4",
				req1: "地脉",
				req2: "史莱姆",
				type: "weapon",
			},
			{
				name: "流浪乐章",
				req: "凛风奔狼",
				region: "蒙德",
				star: "4",
				req1: "地脉",
				req2: "面具",
				type: "weapon",
			},
			{
				name: "决斗之枪",
				req: "凛风奔狼",
				region: "蒙德",
				star: "4",
				req1: "地脉",
				req2: "花蜜",
				type: "weapon",
			},
			{
				name: "龙脊长枪",
				req: "凛风奔狼",
				region: "蒙德",
				star: "4",
				req1: "雾虚",
				req2: "徽记",
				type: "weapon",
			},
		],
		狮牙斗士: [
			{
				name: "狼的末路",
				req: "狮牙斗士",
				region: "蒙德",
				star: "5",
				req1: "混沌",
				req2: "绘卷",
				type: "weapon",
			},
			{
				name: "天空之脊",
				req: "狮牙斗士",
				region: "蒙德",
				star: "5",
				req1: "混沌",
				req2: "绘卷",
				type: "weapon",
			},
			{
				name: "阿莫斯之弓",
				req: "狮牙斗士",
				region: "蒙德",
				star: "5",
				req1: "混沌",
				req2: "史莱姆",
				type: "weapon",
			},
			{
				name: "四风原典",
				req: "狮牙斗士",
				region: "蒙德",
				star: "5",
				req1: "混沌",
				req2: "史莱姆",
				type: "weapon",
			},
			{
				name: "祭礼剑",
				req: "狮牙斗士",
				region: "蒙德",
				star: "4",
				req1: "混沌",
				req2: "绘卷",
				type: "weapon",
			},
			{
				name: "宗室大剑",
				req: "狮牙斗士",
				region: "蒙德",
				star: "4",
				req1: "混沌",
				req2: "史莱姆",
				type: "weapon",
			},
			{
				name: "西风大剑",
				req: "狮牙斗士",
				region: "蒙德",
				star: "4",
				req1: "混沌",
				req2: "徽记",
				type: "weapon",
			},
			{
				name: "西风猎弓",
				req: "狮牙斗士",
				region: "蒙德",
				star: "4",
				req1: "混沌",
				req2: "花蜜",
				type: "weapon",
			},
			{
				name: "祭礼残章",
				req: "狮牙斗士",
				region: "蒙德",
				star: "4",
				req1: "混沌",
				req2: "鸦印",
				type: "weapon",
			},
			{
				name: "忍冬之果",
				req: "狮牙斗士",
				region: "蒙德",
				star: "4",
				req1: "混沌",
				req2: "花蜜",
				type: "weapon",
			},
			{
				name: "西风长枪",
				req: "狮牙斗士",
				region: "蒙德",
				star: "4",
				req1: "混沌",
				req2: "徽记",
				type: "weapon",
			},
			{
				name: "腐殖之剑",
				req: "狮牙斗士",
				region: "蒙德",
				star: "4",
				req1: "号角",
				req2: "徽记",
				type: "weapon",
			},
		],
		漆黑陨铁: [
			{
				name: "尘世之锁",
				req: "漆黑陨铁",
				region: "璃月",
				star: "5",
				req1: "骨片",
				req2: "面具",
				type: "weapon",
			},
			{
				name: "贯虹之槊",
				req: "漆黑陨铁",
				region: "璃月",
				star: "5",
				req1: "骨片",
				req2: "鸦印",
				type: "weapon",
			},
			{
				name: "铁蜂刺",
				req: "漆黑陨铁",
				region: "璃月",
				star: "4",
				req1: "骨片",
				req2: "花蜜",
				type: "weapon",
			},
			{
				name: "试作古华",
				req: "漆黑陨铁",
				region: "璃月",
				star: "4",
				req1: "骨片",
				req2: "面具",
				type: "weapon",
			},
			{
				name: "螭骨剑",
				req: "漆黑陨铁",
				region: "璃月",
				star: "4",
				req1: "骨片",
				req2: "花蜜",
				type: "weapon",
			},
			{
				name: "钢轮弓",
				req: "漆黑陨铁",
				region: "璃月",
				star: "4",
				req1: "骨片",
				req2: "徽记",
				type: "weapon",
			},
			{
				name: "万国诸海图谱",
				req: "漆黑陨铁",
				region: "璃月",
				star: "4",
				req1: "骨片",
				req2: "史莱姆",
				type: "weapon",
			},
			{
				name: "试作星镰",
				req: "漆黑陨铁",
				region: "璃月",
				star: "4",
				req1: "骨片",
				req2: "面具",
				type: "weapon",
			},
		],
		孤云寒林: [
			{
				name: "和璞鸢",
				req: "孤云寒林",
				region: "璃月",
				star: "5",
				req1: "祭刀",
				req2: "徽记",
				type: "weapon",
			},
			{
				name: "斫峰之刃",
				req: "孤云寒林",
				region: "璃月",
				star: "5",
				req1: "祭刀",
				req2: "面具",
				type: "weapon",
			},
			{
				name: "黑岩长剑",
				req: "孤云寒林",
				region: "璃月",
				star: "4",
				req1: "祭刀",
				req2: "箭簇",
				type: "weapon",
			},
			{
				name: "匣里龙吟",
				req: "孤云寒林",
				region: "璃月",
				star: "4",
				req1: "祭刀",
				req2: "鸦印",
				type: "weapon",
			},
			{
				name: "白影剑",
				req: "孤云寒林",
				region: "璃月",
				star: "4",
				req1: "祭刀",
				req2: "鸦印",
				type: "weapon",
			},
			{
				name: "弓藏",
				req: "孤云寒林",
				region: "璃月",
				star: "4",
				req1: "祭刀",
				req2: "面具",
				type: "weapon",
			},
			{
				name: "黑岩战弓",
				req: "孤云寒林",
				region: "璃月",
				star: "4",
				req1: "祭刀",
				req2: "花蜜",
				type: "weapon",
			},
			{
				name: "匣里日月",
				req: "孤云寒林",
				region: "璃月",
				star: "4",
				req1: "祭刀",
				req2: "花蜜",
				type: "weapon",
			},
			{
				name: "黑岩绯玉",
				req: "孤云寒林",
				region: "璃月",
				star: "4",
				req1: "祭刀",
				req2: "绘卷",
				type: "weapon",
			},
			{
				name: "流月针",
				req: "孤云寒林",
				region: "璃月",
				star: "4",
				req1: "祭刀",
				req2: "鸦印",
				type: "weapon",
			},
		],
		雾海云间: [
			{
				name: "无工之剑",
				req: "雾海云间",
				region: "璃月",
				star: "5",
				req1: "雾虚",
				req2: "鸦印",
				type: "weapon",
			},
			{
				name: "试作斩岩",
				req: "雾海云间",
				region: "璃月",
				star: "4",
				req1: "雾虚",
				req2: "徽记",
				type: "weapon",
			},
			{
				name: "黑岩斩刀",
				req: "雾海云间",
				region: "璃月",
				star: "4",
				req1: "雾虚",
				req2: "徽记",
				type: "weapon",
			},
			{
				name: "雨裁",
				req: "雾海云间",
				region: "璃月",
				star: "4",
				req1: "雾虚",
				req2: "绘卷",
				type: "weapon",
			},
			{
				name: "宗室长弓",
				req: "雾海云间",
				region: "璃月",
				star: "4",
				req1: "雾虚",
				req2: "鸦印",
				type: "weapon",
			},
			{
				name: "试作澹月",
				req: "雾海云间",
				region: "璃月",
				star: "4",
				req1: "雾虚",
				req2: "鸦印",
				type: "weapon",
			},
			{
				name: "昭心",
				req: "雾海云间",
				region: "璃月",
				star: "4",
				req1: "雾虚",
				req2: "面具",
				type: "weapon",
			},
			{
				name: "试作金珀",
				req: "雾海云间",
				region: "璃月",
				star: "4",
				req1: "雾虚",
				req2: "箭簇",
				type: "weapon",
			},
			{
				name: "匣里灭辰",
				req: "雾海云间",
				region: "璃月",
				star: "4",
				req1: "雾虚",
				req2: "绘卷",
				type: "weapon",
			},
			{
				name: "黑岩刺枪",
				req: "雾海云间",
				region: "璃月",
				star: "4",
				req1: "雾虚",
				req2: "徽记",
				type: "weapon",
			},
			{
				name: "宗室猎枪",
				req: "雾海云间",
				region: "璃月",
				star: "4",
				req1: "雾虚",
				req2: "徽记",
				type: "weapon",
			},
		],
	},
	chars: {
		繁荣: [
			{
				name: "七七",
				req: "繁荣",
				region: "璃月",
				star: "5",
				req1: "绘卷",
				req2: "北风之尾",
				type: "char",
			},
			{
				name: "刻晴",
				req: "繁荣",
				region: "璃月",
				star: "5",
				req1: "花蜜",
				req2: "北风之环",
				type: "char",
			},
			{
				name: "凝光",
				req: "繁荣",
				region: "璃月",
				star: "4",
				req1: "徽记",
				req2: "北风的魂匣",
				type: "char",
			},
		],
		黄金: [
			{
				name: "钟离",
				req: "黄金",
				region: "璃月",
				star: "5",
				req1: "史莱姆",
				req2: "吞天之鲸·只角",
				type: "char",
			},
			{
				name: "辛焱",
				req: "黄金",
				region: "璃月",
				star: "4",
				req1: "鸦印",
				req2: "吞天之鲸·只角",
				type: "char",
			},
			{
				name: "北斗",
				req: "黄金",
				region: "璃月",
				star: "4",
				req1: "鸦印",
				req2: "东风的吐息",
				type: "char",
			},
			{
				name: "行秋",
				req: "黄金",
				region: "璃月",
				star: "4",
				req1: "面具",
				req2: "北风之尾",
				type: "char",
			},
		],
		自由: [
			{
				name: "达达利亚",
				req: "自由",
				region: "蒙德",
				star: "5",
				req1: "徽记",
				req2: "魔王之刃·残片",
				type: "char",
			},
			{
				name: "可莉",
				req: "自由",
				region: "蒙德",
				star: "5",
				req1: "绘卷",
				req2: "北风之环",
				type: "char",
			},
			{
				name: "安柏",
				req: "自由",
				region: "蒙德",
				star: "4",
				req1: "箭簇",
				req2: "东风的吐息",
				type: "char",
			},
			{
				name: "砂糖",
				req: "自由",
				region: "蒙德",
				star: "4",
				req1: "花蜜",
				req2: "北风的魂匣",
				type: "char",
			},
			{
				name: "芭芭拉",
				req: "自由",
				region: "蒙德",
				star: "4",
				req1: "绘卷",
				req2: "北风之环",
				type: "char",
			},
			{
				name: "迪奥娜",
				req: "自由",
				region: "蒙德",
				star: "4",
				req1: "箭簇",
				req2: "魔王之刃·残片",
				type: "char",
			},
		],
		诗文: [
			{
				name: "温迪",
				req: "诗文",
				region: "蒙德",
				star: "5",
				req1: "史莱姆",
				req2: "北风之尾",
				type: "char",
			},
			{
				name: "阿贝多",
				req: "诗文",
				region: "蒙德",
				star: "5",
				req1: "绘卷",
				req2: "吞天之鲸·只角",
				type: "char",
			},
			{
				name: "丽莎",
				req: "诗文",
				region: "蒙德",
				star: "4",
				req1: "史莱姆",
				req2: "东风之爪",
				type: "char",
			},
			{
				name: "凯亚",
				req: "诗文",
				region: "蒙德",
				star: "4",
				req1: "鸦印",
				req2: "北风的魂匣",
				type: "char",
			},
			{
				name: "菲谢尔",
				req: "诗文",
				region: "蒙德",
				star: "4",
				req1: "箭簇",
				req2: "北风的魂匣",
				type: "char",
			},
		],
		抗争: [
			{
				name: "琴",
				req: "抗争",
				region: "蒙德",
				star: "5",
				req1: "面具",
				req2: "东风之翎",
				type: "char",
			},
			{
				name: "莫娜",
				req: "抗争",
				region: "蒙德",
				star: "5",
				req1: "花蜜",
				req2: "北风之环",
				type: "char",
			},
			{
				name: "迪卢克",
				req: "抗争",
				region: "蒙德",
				star: "5",
				req1: "徽记",
				req2: "东风之翎",
				type: "char",
			},
			{
				name: "班尼特",
				req: "抗争",
				region: "蒙德",
				star: "4",
				req1: "鸦印",
				req2: "东风之翎",
				type: "char",
			},
			{
				name: "诺艾尔",
				req: "抗争",
				region: "蒙德",
				star: "4",
				req1: "面具",
				req2: "东风之爪",
				type: "char",
			},
			{
				name: "雷泽",
				req: "抗争",
				region: "蒙德",
				star: "4",
				req1: "面具",
				req2: "东风之爪",
				type: "char",
			},
		],
		勤劳: [
			{
				name: "重云",
				req: "勤劳",
				region: "璃月",
				star: "4",
				req1: "面具",
				req2: "东风的吐息",
				type: "char",
			},
			{
				name: "香菱",
				req: "勤劳",
				region: "璃月",
				star: "4",
				req1: "史莱姆",
				req2: "东风之爪",
				type: "char",
			},
			{
				name: "甘雨",
				req: "勤劳",
				region: "璃月",
				star: "5",
				req1: "面具",
				req2: "武炼之魂·孤影",
				type: "char",
			},
		],
	},
	char_breakthrough_stats: {
		20: {
			attrib_req_level: 1,
			attrib_req_count: 1,
			champ_req_count: 0,
			world_req_count: 3,
			world_mon_req_level: 1,
			world_mon_req_count: 3,
			mora: 20000,
		},
		40: {
			attrib_req_level: 2,
			attrib_req_count: 3,
			champ_req_count: 2,
			world_req_count: 10,
			world_mon_req_level: 1,
			world_mon_req_count: 15,
			mora: 40000,
		},
		50: {
			attrib_req_level: 2,
			attrib_req_count: 6,
			champ_req_count: 4,
			world_req_count: 20,
			world_mon_req_level: 2,
			world_mon_req_count: 12,
			mora: 60000,
		},
		60: {
			attrib_req_level: 3,
			attrib_req_count: 3,
			champ_req_count: 8,
			world_req_count: 30,
			world_mon_req_level: 2,
			world_mon_req_count: 18,
			mora: 80000,
		},
		70: {
			attrib_req_level: 3,
			attrib_req_count: 6,
			champ_req_count: 12,
			world_req_count: 45,
			world_mon_req_level: 3,
			world_mon_req_count: 12,
			mora: 100000,
		},
		80: {
			attrib_req_level: 4,
			attrib_req_count: 6,
			champ_req_count: 20,
			world_req_count: 60,
			world_mon_req_level: 3,
			world_mon_req_count: 24,
			mora: 120000,
		},
	},
	char_level_stats: [
		0,
		1000,
		1325,
		1700,
		2150,
		2625,
		3150,
		3725,
		4350,
		5000,
		5700,
		6450,
		7225,
		8050,
		8925,
		9825,
		10750,
		11725,
		12725,
		13775,
		14875,
		16800,
		18000,
		19250,
		20550,
		21875,
		23250,
		24650,
		26100,
		27575,
		29100,
		30650,
		32250,
		33875,
		35550,
		37250,
		38975,
		40750,
		42575,
		44425,
		46300,
		50625,
		52700,
		54775,
		56900,
		59075,
		61275,
		63525,
		65800,
		68125,
		70475,
		76500,
		79050,
		81650,
		84275,
		86950,
		89650,
		92400,
		95175,
		98000,
		100875,
		108950,
		112050,
		115175,
		118325,
		121525,
		124775,
		128075,
		131400,
		134775,
		138175,
		148700,
		152375,
		156075,
		159825,
		163600,
		167425,
		171300,
		175225,
		179175,
		183175,
		216225,
		243025,
		273100,
		306800,
		344600,
		386950,
		434425,
		487625,
		547200,
	],
	char_trait_name: {
		凝光: {
			normal_attack: "普通攻击·千金掷",
			elemental_skill: "璇玑屏",
			elemental_burst: "天权崩玉",
		},
		北斗: {
			normal_attack: "普通攻击·征涛",
			elemental_skill: "捉浪",
			elemental_burst: "斫雷",
		},
		行秋: {
			normal_attack: "普通攻击·古华剑法",
			elemental_skill: "古华剑·画雨笼山",
			elemental_burst: "古华剑·裁雨留虹",
		},
		辛焱: {
			normal_attack: "普通攻击·炎舞",
			elemental_skill: "热情拂扫",
			elemental_burst: "叛逆刮弦",
		},
		重云: {
			normal_attack: "普通攻击·灭邪四式",
			elemental_skill: "重华叠霜·灵刃",
			elemental_burst: "灵刃·云开星落",
		},
		香菱: {
			normal_attack: "普通攻击·白案功夫",
			elemental_skill: "锅巴出击",
			elemental_burst: "旋火轮",
		},
		七七: {
			normal_attack: "普通攻击·云来古剑法",
			elemental_skill: "仙法·寒病鬼差",
			elemental_burst: "仙法·救苦度厄",
		},
		刻晴: {
			normal_attack: "普通攻击·云来剑法",
			elemental_skill: "星斗归位",
			elemental_burst: "天街巡游",
		},
		钟离: {
			normal_attack: "普通攻击·岩雨",
			elemental_skill: "元素战技·地心",
			elemental_burst: "元素爆发·天星",
		},
		达达利亚: {
			normal_attack: "普通攻击·断雨",
			elemental_skill: "魔王武装·狂澜",
			elemental_burst: "极恶技·尽灭闪",
		},
		丽莎: {
			normal_attack: "普通攻击·指尖雷暴",
			elemental_skill: "苍雷",
			elemental_burst: "蔷薇的雷光",
		},
		凯亚: {
			normal_attack: "普通攻击·仪典剑术",
			elemental_skill: "霜袭",
			elemental_burst: "凛冽轮舞",
		},
		安柏: {
			normal_attack: "普通攻击·神射手",
			elemental_skill: "爆弹玩偶",
			elemental_burst: "箭雨",
		},
		班尼特: {
			normal_attack: "普通攻击·好运剑",
			elemental_skill: "热情过载",
			elemental_burst: "美妙旅程",
		},
		砂糖: {
			normal_attack: "普通攻击·简式风灵作成",
			elemental_skill: "风灵作成·陆叁零捌",
			elemental_burst: "禁·风灵作成·柒伍同构贰型",
		},
		芭芭拉: {
			normal_attack: "普通攻击·水之浅唱",
			elemental_skill: "演唱，开始♪",
			elemental_burst: "闪耀奇迹♪",
		},
		菲谢尔: {
			normal_attack: "普通攻击·罪灭之矢",
			elemental_skill: "夜巡影翼",
			elemental_burst: "至夜幻现",
		},
		诺艾尔: {
			normal_attack: "普通攻击·西风剑术·女仆",
			elemental_skill: "护心铠",
			elemental_burst: "大扫除",
		},
		迪奥娜: {
			normal_attack: "普通攻击·猎人射术",
			elemental_skill: "猫爪冻冻",
			elemental_burst: "最烈特调",
		},
		雷泽: {
			normal_attack: "普通攻击·钢脊",
			elemental_skill: "利爪与苍雷",
			elemental_burst: "雷牙",
		},
		可莉: {
			normal_attack: "普通攻击·砰砰",
			elemental_skill: "蹦蹦炸弹",
			elemental_burst: "轰轰火花",
		},
		温迪: {
			normal_attack: "普通攻击·神代射术",
			elemental_skill: "高天之歌",
			elemental_burst: "风神之诗",
		},
		琴: {
			normal_attack: "普通攻击·西风剑术",
			elemental_skill: "风压剑",
			elemental_burst: "蒲公英之风",
		},
		莫娜: {
			normal_attack: "普通攻击·因果点破",
			elemental_skill: "水中幻愿",
			elemental_burst: "星命定轨",
		},
		迪卢克: {
			normal_attack: "普通攻击·淬炼之剑",
			elemental_skill: "逆焰之刃",
			elemental_burst: "黎明",
		},
		阿贝多: {
			normal_attack: "普通攻击·西风剑术·白",
			elemental_skill: "创生法·拟造阳华",
			elemental_burst: "诞生式·大地之潮",
		},
	},
	char_reqs: {
		凝光: {
			star: "4",
			element: "岩",
			attrib_req: "坚牢黄玉",
			champ_attrib_req: "玄岩之塔",
			world_req: "琉璃百合",
			world_mon_req: "徽记",
			trait_req: "北风的魂匣",
			trait_daily: "繁荣",
		},
		北斗: {
			star: "4",
			element: "雷",
			attrib_req: "最胜紫晶",
			champ_attrib_req: "雷光棱镜",
			world_req: "夜泊石",
			world_mon_req: "鸦印",
			trait_req: "东风的吐息",
			trait_daily: "黄金",
		},
		行秋: {
			star: "4",
			element: "水",
			attrib_req: "涤净青金",
			champ_attrib_req: "净水之心",
			world_req: "霓裳花",
			world_mon_req: "面具",
			trait_req: "北风之尾",
			trait_daily: "黄金",
		},
		辛焱: {
			star: "4",
			element: "火",
			attrib_req: "燃愿玛瑙",
			champ_attrib_req: "常燃火种",
			world_req: "琉璃袋",
			world_mon_req: "鸦印",
			trait_req: "吞天之鲸·只角",
			trait_daily: "黄金",
		},
		重云: {
			star: "4",
			element: "冰",
			attrib_req: "哀叙冰玉",
			champ_attrib_req: "极寒之核",
			world_req: "石珀",
			world_mon_req: "面具",
			trait_req: "东风的吐息",
			trait_daily: "勤劳",
		},
		香菱: {
			star: "4",
			element: "火",
			attrib_req: "燃愿玛瑙",
			champ_attrib_req: "常燃火种",
			world_req: "绝云椒椒",
			world_mon_req: "史莱姆",
			trait_req: "东风之爪",
			trait_daily: "勤劳",
		},
		七七: {
			star: "5",
			element: "冰",
			attrib_req: "哀叙冰玉",
			champ_attrib_req: "极寒之核",
			world_req: "琉璃袋",
			world_mon_req: "绘卷",
			trait_req: "北风之尾",
			trait_daily: "繁荣",
		},
		刻晴: {
			star: "5",
			element: "雷",
			attrib_req: "最胜紫晶",
			champ_attrib_req: "雷光棱镜",
			world_req: "石珀",
			world_mon_req: "花蜜",
			trait_req: "北风之环",
			trait_daily: "繁荣",
		},
		钟离: {
			star: "5",
			element: "岩",
			attrib_req: "坚牢黄玉",
			champ_attrib_req: "玄岩之塔",
			world_req: "石珀",
			world_mon_req: "史莱姆",
			trait_req: "吞天之鲸·只角",
			trait_daily: "黄金",
		},
		达达利亚: {
			star: "5",
			element: "水",
			attrib_req: "涤净青金",
			champ_attrib_req: "净水之心",
			world_req: "星螺",
			world_mon_req: "徽记",
			trait_req: "魔王之刃·残片",
			trait_daily: "自由",
		},
		丽莎: {
			star: "4",
			element: "雷",
			attrib_req: "最胜紫晶",
			champ_attrib_req: "雷光棱镜",
			world_req: "落落莓",
			world_mon_req: "史莱姆",
			trait_req: "东风之爪",
			trait_daily: "诗文",
		},
		凯亚: {
			star: "4",
			element: "冰",
			attrib_req: "哀叙冰玉",
			champ_attrib_req: "极寒之核",
			world_req: "嘟嘟莲",
			world_mon_req: "鸦印",
			trait_req: "北风的魂匣",
			trait_daily: "诗文",
		},
		安柏: {
			star: "4",
			element: "火",
			attrib_req: "燃愿玛瑙",
			champ_attrib_req: "常燃火种",
			world_req: "小灯草",
			world_mon_req: "箭簇",
			trait_req: "东风的吐息",
			trait_daily: "自由",
		},
		班尼特: {
			star: "4",
			element: "火",
			attrib_req: "燃愿玛瑙",
			champ_attrib_req: "常燃火种",
			world_req: "风车菊",
			world_mon_req: "鸦印",
			trait_req: "东风之翎",
			trait_daily: "抗争",
		},
		砂糖: {
			star: "4",
			element: "风",
			attrib_req: "自在松石",
			champ_attrib_req: "飓风之种",
			world_req: "风车菊",
			world_mon_req: "花蜜",
			trait_req: "北风的魂匣",
			trait_daily: "自由",
		},
		芭芭拉: {
			star: "4",
			element: "水",
			attrib_req: "涤净青金",
			champ_attrib_req: "净水之心",
			world_req: "慕风蘑菇",
			world_mon_req: "绘卷",
			trait_req: "北风之环",
			trait_daily: "自由",
		},
		菲谢尔: {
			star: "4",
			element: "雷",
			attrib_req: "最胜紫晶",
			champ_attrib_req: "雷光棱镜",
			world_req: "小灯草",
			world_mon_req: "箭簇",
			trait_req: "北风的魂匣",
			trait_daily: "诗文",
		},
		诺艾尔: {
			star: "4",
			element: "岩",
			attrib_req: "坚牢黄玉",
			champ_attrib_req: "玄岩之塔",
			world_req: "落落莓",
			world_mon_req: "面具",
			trait_req: "东风之爪",
			trait_daily: "抗争",
		},
		迪奥娜: {
			star: "4",
			element: "冰",
			attrib_req: "哀叙冰玉",
			champ_attrib_req: "极寒之核",
			world_req: "嘟嘟莲",
			world_mon_req: "箭簇",
			trait_req: "魔王之刃·残片",
			trait_daily: "自由",
		},
		雷泽: {
			star: "4",
			element: "雷",
			attrib_req: "最胜紫晶",
			champ_attrib_req: "雷光棱镜",
			world_req: "钩钩果",
			world_mon_req: "面具",
			trait_req: "东风之爪",
			trait_daily: "抗争",
		},
		可莉: {
			star: "5",
			element: "火",
			attrib_req: "燃愿玛瑙",
			champ_attrib_req: "常燃火种",
			world_req: "慕风蘑菇",
			world_mon_req: "绘卷",
			trait_req: "北风之环",
			trait_daily: "自由",
		},
		温迪: {
			star: "5",
			element: "风",
			attrib_req: "自在松石",
			champ_attrib_req: "飓风之种",
			world_req: "塞西莉亚花",
			world_mon_req: "史莱姆",
			trait_req: "北风之尾",
			trait_daily: "诗文",
		},
		琴: {
			star: "5",
			element: "风",
			attrib_req: "自在松石",
			champ_attrib_req: "飓风之种",
			world_req: "蒲公英籽",
			world_mon_req: "面具",
			trait_req: "东风之翎",
			trait_daily: "抗争",
		},
		莫娜: {
			star: "5",
			element: "水",
			attrib_req: "涤净青金",
			champ_attrib_req: "净水之心",
			world_req: "慕风蘑菇",
			world_mon_req: "花蜜",
			trait_req: "北风之环",
			trait_daily: "抗争",
		},
		迪卢克: {
			star: "5",
			element: "火",
			attrib_req: "燃愿玛瑙",
			champ_attrib_req: "常燃火种",
			world_req: "小灯草",
			world_mon_req: "徽记",
			trait_req: "东风之翎",
			trait_daily: "抗争",
		},
		阿贝多: {
			star: "5",
			element: "岩",
			attrib_req: "坚牢黄玉",
			champ_attrib_req: "玄岩之塔",
			world_req: "塞西莉亚花",
			world_mon_req: "面具",
			trait_req: "东风之爪",
			trait_daily: "诗文",
		},
		甘雨: {
			star: "5",
			element: "冰",
			attrib_req: "哀叙冰玉",
			champ_attrib_req: "极寒之核",
			world_req: "清心",
			world_mon_req: "花蜜",
			trait_req: "武炼之魂·孤影",
			trait_daily: "勤劳",
		},
	},
	name_transform: {
		坚牢黄玉1: "坚牢黄玉碎屑",
		坚牢黄玉2: "坚牢黄玉断片",
		坚牢黄玉3: "坚牢黄玉块",
		坚牢黄玉4: "坚牢黄玉",
		璀璨原钻1: "璀璨原钻碎屑",
		璀璨原钻2: "璀璨原钻断片",
		璀璨原钻3: "璀璨原钻块",
		璀璨原钻4: "璀璨原钻",
		燃愿玛瑙1: "燃愿玛瑙碎屑",
		燃愿玛瑙2: "燃愿玛瑙断片",
		燃愿玛瑙3: "燃愿玛瑙块",
		燃愿玛瑙4: "燃愿玛瑙",
		哀叙冰玉1: "哀叙冰玉碎屑",
		哀叙冰玉2: "哀叙冰玉断片",
		哀叙冰玉3: "哀叙冰玉块",
		哀叙冰玉4: "哀叙冰玉",
		涤净青金1: "涤净青金碎屑",
		涤净青金2: "涤净青金断片",
		涤净青金3: "涤净青金块",
		涤净青金4: "涤净青金",
		最胜紫晶1: "最胜紫晶碎屑",
		最胜紫晶2: "最胜紫晶断片",
		最胜紫晶3: "最胜紫晶块",
		最胜紫晶4: "最胜紫晶",
		自在松石1: "自在松石碎屑",
		自在松石2: "自在松石断片",
		自在松石3: "自在松石块",
		自在松石4: "自在松石",
		面具1: "破损的面具",
		面具2: "污秽的面具",
		面具3: "不祥的面具",
		徽记1: "新兵的徽记",
		徽记2: "士官的徽记",
		徽记3: "尉官的徽记",
		鸦印1: "寻宝鸦印",
		鸦印2: "藏银鸦印",
		鸦印3: "攫金鸦印",
		史莱姆1: "史莱姆凝液",
		史莱姆2: "史莱姆清",
		史莱姆3: "史莱姆原浆",
		绘卷1: "导能绘卷",
		绘卷2: "封魔绘卷",
		绘卷3: "禁咒绘卷",
		花蜜1: "骗骗花蜜",
		花蜜2: "微光花蜜",
		花蜜3: "原素花蜜",
		箭簇1: "牢固的箭簇",
		箭簇2: "锐利的箭簇",
		箭簇3: "历战的箭簇",
		地脉1: "地脉的旧枝",
		地脉2: "地脉的枯叶",
		地脉3: "地脉的新芽",
		骨片1: "脆弱的骨片",
		骨片2: "结实的骨片",
		骨片3: "石化的骨片",
		号角1: "沉重号角",
		号角2: "黑铜号角",
		号角3: "黑晶号角",
		混沌1: "混沌装置",
		混沌2: "混沌回路",
		混沌3: "混沌炉心",
		祭刀1: "猎兵祭刀",
		祭刀2: "特工祭刀",
		祭刀3: "督察长祭刀",
		雾虚1: "雾虚花粉",
		雾虚2: "雾虚草囊",
		雾虚3: "雾虚灯芯",
		凛风奔狼1: "凛风奔狼的始龀",
		凛风奔狼2: "凛风奔狼的裂齿",
		凛风奔狼3: "凛风奔狼的断牙",
		凛风奔狼4: "凛风奔狼的怀乡",
		高塔孤王1: "高塔孤王的破瓦",
		高塔孤王2: "高塔孤王的残垣",
		高塔孤王3: "高塔孤王的断片",
		高塔孤王4: "高塔孤王的碎梦",
		孤云寒林1: "孤云寒林的光砂",
		孤云寒林2: "孤云寒林的辉岩",
		孤云寒林3: "孤云寒林的圣骸",
		孤云寒林4: "孤云寒林的神体",
		雾海云间1: "雾海云间的铅丹",
		雾海云间2: "雾海云间的汞丹",
		雾海云间3: "雾海云间的金丹",
		雾海云间4: "雾海云间的转还",
		狮牙斗士1: "狮牙斗士的枷锁",
		狮牙斗士2: "狮牙斗士的铁链",
		狮牙斗士3: "狮牙斗士的镣铐",
		狮牙斗士4: "狮牙斗士的理想",
		漆黑陨铁1: "漆黑陨铁的一粒",
		漆黑陨铁2: "漆黑陨铁的一片",
		漆黑陨铁3: "漆黑陨铁的一角",
		漆黑陨铁4: "漆黑陨铁的一块",
		自由1: "自由的教导",
		自由2: "自由的指引",
		自由3: "自由的哲学",
		诗文1: "诗文的教导",
		诗文2: "诗文的指引",
		诗文3: "诗文的哲学",
		抗争1: "抗争的教导",
		抗争2: "抗争的指引",
		抗争3: "抗争的哲学",
		繁荣1: "繁荣的教导",
		繁荣2: "繁荣的指引",
		繁荣3: "繁荣的哲学",
		勤劳1: "勤劳的教导",
		勤劳2: "勤劳的指引",
		勤劳3: "勤劳的哲学",
		黄金1: "黄金的教导",
		黄金2: "黄金的指引",
		黄金3: "黄金的哲学",
	},
	item_rarity: {
		坚牢黄玉碎屑: 2,
		坚牢黄玉断片: 3,
		坚牢黄玉块: 4,
		坚牢黄玉: 5,
		璀璨原钻碎屑: 2,
		璀璨原钻断片: 3,
		璀璨原钻块: 4,
		璀璨原钻: 5,
		燃愿玛瑙碎屑: 2,
		燃愿玛瑙断片: 3,
		燃愿玛瑙块: 4,
		燃愿玛瑙: 5,
		哀叙冰玉碎屑: 2,
		哀叙冰玉断片: 3,
		哀叙冰玉块: 4,
		哀叙冰玉: 5,
		涤净青金碎屑: 2,
		涤净青金断片: 3,
		涤净青金块: 4,
		涤净青金: 5,
		最胜紫晶碎屑: 2,
		最胜紫晶断片: 3,
		最胜紫晶块: 4,
		最胜紫晶: 5,
		自在松石碎屑: 2,
		自在松石断片: 3,
		自在松石块: 4,
		自在松石: 5,
		破损的面具: 1,
		污秽的面具: 2,
		不祥的面具: 3,
		新兵的徽记: 1,
		士官的徽记: 2,
		尉官的徽记: 3,
		寻宝鸦印: 1,
		藏银鸦印: 2,
		攫金鸦印: 3,
		史莱姆凝液: 1,
		史莱姆清: 2,
		史莱姆原浆: 3,
		导能绘卷: 1,
		封魔绘卷: 2,
		禁咒绘卷: 3,
		骗骗花蜜: 1,
		微光花蜜: 2,
		原素花蜜: 3,
		牢固的箭簇: 1,
		锐利的箭簇: 2,
		历战的箭簇: 3,
		地脉的旧枝: 2,
		地脉的枯叶: 3,
		地脉的新芽: 4,
		脆弱的骨片: 2,
		结实的骨片: 3,
		石化的骨片: 4,
		沉重号角: 2,
		黑铜号角: 3,
		黑晶号角: 4,
		混沌装置: 2,
		混沌回路: 3,
		混沌炉心: 4,
		猎兵祭刀: 2,
		特工祭刀: 3,
		督察长祭刀: 4,
		雾虚花粉: 2,
		雾虚草囊: 3,
		雾虚灯芯: 4,
		东风之爪: 5,
		东风之翎: 5,
		东风的吐息: 5,
		北风之尾: 5,
		北风之环: 5,
		北风的魂匣: 5,
		"吞天之鲸·只角": 5,
		"魔王之刃·残片": 5,
		"武炼之魂·孤影": 5,
		玄岩之塔: 4,
		雷光棱镜: 4,
		净水之心: 4,
		常燃火种: 4,
		极寒之核: 4,
		飓风之种: 4,
		嘟嘟莲: 1,
		落落莓: 1,
		塞西莉亚花: 1,
		小灯草: 1,
		慕风蘑菇: 1,
		蒲公英籽: 1,
		钩钩果: 1,
		风车菊: 1,
		夜泊石: 1,
		绝云椒椒: 1,
		霓裳花: 1,
		琉璃百合: 1,
		清心: 1,
		星螺: 1,
		琉璃袋: 1,
		石珀: 1,
		凛风奔狼的始龀: 2,
		凛风奔狼的裂齿: 3,
		凛风奔狼的断牙: 4,
		凛风奔狼的怀乡: 5,
		高塔孤王的破瓦: 2,
		高塔孤王的残垣: 3,
		高塔孤王的断片: 4,
		高塔孤王的碎梦: 5,
		孤云寒林的光砂: 2,
		孤云寒林的辉岩: 3,
		孤云寒林的圣骸: 4,
		孤云寒林的神体: 5,
		雾海云间的铅丹: 2,
		雾海云间的汞丹: 3,
		雾海云间的金丹: 4,
		雾海云间的转还: 5,
		狮牙斗士的枷锁: 2,
		狮牙斗士的铁链: 3,
		狮牙斗士的镣铐: 4,
		狮牙斗士的理想: 5,
		漆黑陨铁的一粒: 2,
		漆黑陨铁的一片: 3,
		漆黑陨铁的一角: 4,
		漆黑陨铁的一块: 5,
		自由的教导: 2,
		自由的指引: 3,
		自由的哲学: 4,
		诗文的教导: 2,
		诗文的指引: 3,
		诗文的哲学: 4,
		抗争的教导: 2,
		抗争的指引: 3,
		抗争的哲学: 4,
		繁荣的教导: 2,
		繁荣的指引: 3,
		繁荣的哲学: 4,
		勤劳的教导: 2,
		勤劳的指引: 3,
		勤劳的哲学: 4,
		黄金的教导: 2,
		黄金的指引: 3,
		黄金的哲学: 4,
		智识之冕: 5,
	},
	traits_leeling_stats: {
		2: {
			daily_req_level: 1,
			daily_req_count: 3,
			world_mon_req_level: 1,
			world_mon_req_count: 6,
			boss_req_count: 0,
			crown_req_count: 0,
			mora: 12500,
		},
		3: {
			daily_req_level: 2,
			daily_req_count: 2,
			world_mon_req_level: 2,
			world_mon_req_count: 3,
			boss_req_count: 0,
			crown_req_count: 0,
			mora: 17500,
		},
		4: {
			daily_req_level: 2,
			daily_req_count: 4,
			world_mon_req_level: 2,
			world_mon_req_count: 4,
			boss_req_count: 0,
			crown_req_count: 0,
			mora: 25000,
		},
		5: {
			daily_req_level: 2,
			daily_req_count: 6,
			world_mon_req_level: 2,
			world_mon_req_count: 6,
			boss_req_count: 0,
			crown_req_count: 0,
			mora: 30000,
		},
		6: {
			daily_req_level: 2,
			daily_req_count: 9,
			world_mon_req_level: 2,
			world_mon_req_count: 9,
			boss_req_count: 0,
			crown_req_count: 0,
			mora: 37500,
		},
		7: {
			daily_req_level: 3,
			daily_req_count: 4,
			world_mon_req_level: 3,
			world_mon_req_count: 4,
			boss_req_count: 1,
			crown_req_count: 0,
			mora: 120000,
		},
		8: {
			daily_req_level: 3,
			daily_req_count: 6,
			world_mon_req_level: 3,
			world_mon_req_count: 6,
			boss_req_count: 1,
			crown_req_count: 0,
			mora: 260000,
		},
		9: {
			daily_req_level: 3,
			daily_req_count: 12,
			world_mon_req_level: 3,
			world_mon_req_count: 9,
			boss_req_count: 2,
			crown_req_count: 0,
			mora: 450000,
		},
		10: {
			daily_req_level: 3,
			daily_req_count: 16,
			world_mon_req_level: 3,
			world_mon_req_count: 16,
			boss_req_count: 2,
			crown_req_count: 1,
			mora: 700000,
		},
	},
	weapon_breakthrough_stats: {
		4: {
			20: {
				daily_req_level: 1,
				daily_req_count: 3,
				champ_attrib_req_level: 1,
				champ_attrib_req_count: 3,
				world_mon_req_level: 1,
				world_mon_req_count: 2,
				mora: 5000,
			},
			40: {
				daily_req_level: 2,
				daily_req_count: 3,
				champ_attrib_req_level: 1,
				champ_attrib_req_count: 12,
				world_mon_req_level: 1,
				world_mon_req_count: 8,
				mora: 15000,
			},
			50: {
				daily_req_level: 2,
				daily_req_count: 6,
				champ_attrib_req_level: 2,
				champ_attrib_req_count: 6,
				world_mon_req_level: 2,
				world_mon_req_count: 6,
				mora: 20000,
			},
			60: {
				daily_req_level: 3,
				daily_req_count: 3,
				champ_attrib_req_level: 2,
				champ_attrib_req_count: 12,
				world_mon_req_level: 2,
				world_mon_req_count: 9,
				mora: 30000,
			},
			70: {
				daily_req_level: 3,
				daily_req_count: 6,
				champ_attrib_req_level: 3,
				champ_attrib_req_count: 9,
				world_mon_req_level: 3,
				world_mon_req_count: 6,
				mora: 35000,
			},
			80: {
				daily_req_level: 4,
				daily_req_count: 4,
				champ_attrib_req_level: 3,
				champ_attrib_req_count: 18,
				world_mon_req_level: 3,
				world_mon_req_count: 12,
				mora: 45000,
			},
		},
		5: {
			20: {
				daily_req_level: 1,
				daily_req_count: 5,
				champ_attrib_req_level: 1,
				champ_attrib_req_count: 5,
				world_mon_req_level: 1,
				world_mon_req_count: 3,
				mora: 10000,
			},
			40: {
				daily_req_level: 2,
				daily_req_count: 5,
				champ_attrib_req_level: 1,
				champ_attrib_req_count: 18,
				world_mon_req_level: 1,
				world_mon_req_count: 12,
				mora: 20000,
			},
			50: {
				daily_req_level: 2,
				daily_req_count: 9,
				champ_attrib_req_level: 2,
				champ_attrib_req_count: 9,
				world_mon_req_level: 2,
				world_mon_req_count: 9,
				mora: 30000,
			},
			60: {
				daily_req_level: 3,
				daily_req_count: 5,
				champ_attrib_req_level: 2,
				champ_attrib_req_count: 18,
				world_mon_req_level: 2,
				world_mon_req_count: 3,
				mora: 45000,
			},
			70: {
				daily_req_level: 3,
				daily_req_count: 9,
				champ_attrib_req_level: 3,
				champ_attrib_req_count: 14,
				world_mon_req_level: 3,
				world_mon_req_count: 9,
				mora: 55000,
			},
			80: {
				daily_req_level: 4,
				daily_req_count: 6,
				champ_attrib_req_level: 3,
				champ_attrib_req_count: 27,
				world_mon_req_level: 3,
				world_mon_req_count: 18,
				mora: 65000,
			},
		},
	},
	weapon_level_stats: {
		4: [
			0,
			400,
			625,
			900,
			1200,
			1550,
			1950,
			2350,
			2800,
			3300,
			3800,
			4350,
			4925,
			5525,
			6150,
			6800,
			7500,
			8200,
			8950,
			9725,
			10500,
			11900,
			12775,
			13700,
			14650,
			15625,
			16625,
			17650,
			18700,
			19775,
			20900,
			22025,
			23200,
			24375,
			25600,
			26825,
			28100,
			29400,
			30725,
			32075,
			33425,
			36575,
			38075,
			39600,
			41150,
			42725,
			44325,
			45950,
			47600,
			49300,
			51000,
			55375,
			57225,
			59100,
			61025,
			62950,
			64925,
			66900,
			68925,
			70975,
			73050,
			78900,
			81125,
			83400,
			85700,
			88025,
			90375,
			92750,
			95150,
			97575,
			100050,
			107675,
			110325,
			113000,
			115700,
			118425,
			121200,
			124000,
			126825,
			129675,
			132575,
			156475,
			175875,
			197600,
			221975,
			249300,
			279950,
			314250,
			352700,
			395775,
		],
		5: [
			0,
			600,
			950,
			1350,
			1800,
			2325,
			2925,
			3525,
			4200,
			4950,
			5700,
			6525,
			7400,
			8300,
			9225,
			10200,
			11250,
			12300,
			13425,
			14600,
			15750,
			17850,
			19175,
			20550,
			21975,
			23450,
			24950,
			26475,
			28050,
			29675,
			31350,
			33050,
			34800,
			36575,
			38400,
			40250,
			42150,
			44100,
			46100,
			48125,
			50150,
			54875,
			57125,
			59400,
			61725,
			64100,
			66500,
			68925,
			71400,
			73950,
			76500,
			83075,
			85850,
			88650,
			91550,
			94425,
			97400,
			100350,
			103400,
			106475,
			109575,
			118350,
			121700,
			125100,
			128550,
			132050,
			135575,
			139125,
			142725,
			146375,
			150075,
			161525,
			165500,
			169500,
			173550,
			177650,
			181800,
			186000,
			190250,
			194525,
			198875,
			234725,
			263825,
			296400,
			332975,
			373950,
			419925,
			471375,
			529050,
			593675,
		],
	},
	weapon_reqs: {
		风鹰剑: {
			star: "5",
			form: "单手剑",
			daily_req: "高塔孤王",
			champ_attrib_req: "号角",
			world_mon_req: "箭簇",
		},
		天空之刃: {
			star: "5",
			form: "单手剑",
			daily_req: "凛风奔狼",
			champ_attrib_req: "地脉",
			world_mon_req: "史莱姆",
		},
		斫峰之刃: {
			star: "5",
			form: "单手剑",
			daily_req: "孤云寒林",
			champ_attrib_req: "祭刀",
			world_mon_req: "面具",
		},
		匣里龙吟: {
			star: "4",
			form: "单手剑",
			daily_req: "孤云寒林",
			champ_attrib_req: "祭刀",
			world_mon_req: "鸦印",
		},
		西风剑: {
			star: "4",
			form: "单手剑",
			daily_req: "高塔孤王",
			champ_attrib_req: "号角",
			world_mon_req: "箭簇",
		},
		笛剑: {
			star: "4",
			form: "单手剑",
			daily_req: "凛风奔狼",
			champ_attrib_req: "地脉",
			world_mon_req: "史莱姆",
		},
		黑剑: {
			star: "4",
			form: "单手剑",
			daily_req: "凛风奔狼",
			champ_attrib_req: "地脉",
			world_mon_req: "史莱姆",
		},
		祭礼剑: {
			star: "4",
			form: "单手剑",
			daily_req: "狮牙斗士",
			champ_attrib_req: "混沌",
			world_mon_req: "绘卷",
		},
		铁蜂刺: {
			star: "4",
			form: "单手剑",
			daily_req: "漆黑陨铁",
			champ_attrib_req: "骨片",
			world_mon_req: "花蜜",
		},
		试作斩岩: {
			star: "4",
			form: "单手剑",
			daily_req: "雾海云间",
			champ_attrib_req: "雾虚",
			world_mon_req: "徽记",
		},
		宗室长剑: {
			star: "4",
			form: "单手剑",
			daily_req: "高塔孤王",
			champ_attrib_req: "号角",
			world_mon_req: "面具",
		},
		黑岩长剑: {
			star: "4",
			form: "单手剑",
			daily_req: "孤云寒林",
			champ_attrib_req: "祭刀",
			world_mon_req: "箭簇",
		},
		腐殖之剑: {
			star: "4",
			form: "单手剑",
			daily_req: "狮牙斗士",
			champ_attrib_req: "号角",
			world_mon_req: "徽记",
		},
		四风原典: {
			star: "5",
			form: "法器",
			daily_req: "狮牙斗士",
			champ_attrib_req: "混沌",
			world_mon_req: "史莱姆",
		},
		天空之卷: {
			star: "5",
			form: "法器",
			daily_req: "凛风奔狼",
			champ_attrib_req: "地脉",
			world_mon_req: "箭簇",
		},
		尘世之锁: {
			star: "5",
			form: "法器",
			daily_req: "漆黑陨铁",
			champ_attrib_req: "骨片",
			world_mon_req: "面具",
		},
		西风秘典: {
			star: "4",
			form: "法器",
			daily_req: "高塔孤王",
			champ_attrib_req: "号角",
			world_mon_req: "绘卷",
		},
		匣里日月: {
			star: "4",
			form: "法器",
			daily_req: "孤云寒林",
			champ_attrib_req: "祭刀",
			world_mon_req: "花蜜",
		},
		祭礼残章: {
			star: "4",
			form: "法器",
			daily_req: "狮牙斗士",
			champ_attrib_req: "混沌",
			world_mon_req: "鸦印",
		},
		试作金珀: {
			star: "4",
			form: "法器",
			daily_req: "雾海云间",
			champ_attrib_req: "雾虚",
			world_mon_req: "箭簇",
		},
		万国诸海图谱: {
			star: "4",
			form: "法器",
			daily_req: "漆黑陨铁",
			champ_attrib_req: "骨片",
			world_mon_req: "史莱姆",
		},
		昭心: {
			star: "4",
			form: "法器",
			daily_req: "雾海云间",
			champ_attrib_req: "雾虚",
			world_mon_req: "面具",
		},
		流浪乐章: {
			star: "4",
			form: "法器",
			daily_req: "凛风奔狼",
			champ_attrib_req: "地脉",
			world_mon_req: "面具",
		},
		宗室秘法录: {
			star: "4",
			form: "法器",
			daily_req: "高塔孤王",
			champ_attrib_req: "号角",
			world_mon_req: "徽记",
		},
		黑岩绯玉: {
			star: "4",
			form: "法器",
			daily_req: "孤云寒林",
			champ_attrib_req: "祭刀",
			world_mon_req: "绘卷",
		},
		天空之翼: {
			star: "5",
			form: "弓",
			daily_req: "凛风奔狼",
			champ_attrib_req: "地脉",
			world_mon_req: "箭簇",
		},
		阿莫斯之弓: {
			star: "5",
			form: "弓",
			daily_req: "狮牙斗士",
			champ_attrib_req: "混沌",
			world_mon_req: "史莱姆",
		},
		绝弦: {
			star: "4",
			form: "弓",
			daily_req: "高塔孤王",
			champ_attrib_req: "号角",
			world_mon_req: "箭簇",
		},
		苍翠猎弓: {
			star: "4",
			form: "弓",
			daily_req: "高塔孤王",
			champ_attrib_req: "号角",
			world_mon_req: "箭簇",
		},
		祭礼弓: {
			star: "4",
			form: "弓",
			daily_req: "凛风奔狼",
			champ_attrib_req: "地脉",
			world_mon_req: "史莱姆",
		},
		西风猎弓: {
			star: "4",
			form: "弓",
			daily_req: "狮牙斗士",
			champ_attrib_req: "混沌",
			world_mon_req: "花蜜",
		},
		宗室长弓: {
			star: "4",
			form: "弓",
			daily_req: "狮牙斗士",
			champ_attrib_req: "混沌",
			world_mon_req: "绘卷",
		},
		钢轮弓: {
			star: "4",
			form: "弓",
			daily_req: "漆黑陨铁",
			champ_attrib_req: "骨片",
			world_mon_req: "徽记",
		},
		试作澹月: {
			star: "4",
			form: "弓",
			daily_req: "雾海云间",
			champ_attrib_req: "雾虚",
			world_mon_req: "鸦印",
		},
		弓藏: {
			star: "4",
			form: "弓",
			daily_req: "孤云寒林",
			champ_attrib_req: "祭刀",
			world_mon_req: "面具",
		},
		黑岩战弓: {
			star: "4",
			form: "弓",
			daily_req: "孤云寒林",
			champ_attrib_req: "祭刀",
			world_mon_req: "花蜜",
		},
		狼的末路: {
			star: "5",
			form: "双手剑",
			daily_req: "狮牙斗士",
			champ_attrib_req: "混沌",
			world_mon_req: "绘卷",
		},
		天空之傲: {
			star: "5",
			form: "双手剑",
			daily_req: "凛风奔狼",
			champ_attrib_req: "地脉",
			world_mon_req: "史莱姆",
		},
		试作古华: {
			star: "4",
			form: "双手剑",
			daily_req: "漆黑陨铁",
			champ_attrib_req: "骨片",
			world_mon_req: "面具",
		},
		宗室大剑: {
			star: "4",
			form: "双手剑",
			daily_req: "狮牙斗士",
			champ_attrib_req: "混沌",
			world_mon_req: "史莱姆",
		},
		螭骨剑: {
			star: "4",
			form: "双手剑",
			daily_req: "漆黑陨铁",
			champ_attrib_req: "骨片",
			world_mon_req: "花蜜",
		},
		白影剑: {
			star: "4",
			form: "双手剑",
			daily_req: "孤云寒林",
			champ_attrib_req: "祭刀",
			world_mon_req: "鸦印",
		},
		西风大剑: {
			star: "4",
			form: "双手剑",
			daily_req: "狮牙斗士",
			champ_attrib_req: "混沌",
			world_mon_req: "徽记",
		},
		雨裁: {
			star: "4",
			form: "双手剑",
			daily_req: "雾海云间",
			champ_attrib_req: "雾虚",
			world_mon_req: "绘卷",
		},
		祭礼大剑: {
			star: "4",
			form: "双手剑",
			daily_req: "凛风奔狼",
			champ_attrib_req: "地脉",
			world_mon_req: "箭簇",
		},
		钟剑: {
			star: "4",
			form: "双手剑",
			daily_req: "高塔孤王",
			champ_attrib_req: "号角",
			world_mon_req: "花蜜",
		},
		黑岩斩刀: {
			star: "4",
			form: "双手剑",
			daily_req: "雾海云间",
			champ_attrib_req: "雾虚",
			world_mon_req: "徽记",
		},
		无工之剑: {
			star: "5",
			form: "双手剑",
			daily_req: "雾海云间",
			champ_attrib_req: "雾虚",
			world_mon_req: "鸦印",
		},
		和璞鸢: {
			star: "5",
			form: "长柄武器",
			daily_req: "孤云寒林",
			champ_attrib_req: "祭刀",
			world_mon_req: "徽记",
		},
		天空之脊: {
			star: "5",
			form: "长柄武器",
			daily_req: "狮牙斗士",
			champ_attrib_req: "混沌",
			world_mon_req: "绘卷",
		},
		流月针: {
			star: "4",
			form: "长柄武器",
			daily_req: "孤云寒林",
			champ_attrib_req: "祭刀",
			world_mon_req: "鸦印",
		},
		试作星镰: {
			star: "4",
			form: "长柄武器",
			daily_req: "漆黑陨铁",
			champ_attrib_req: "骨片",
			world_mon_req: "面具",
		},
		西风长枪: {
			star: "4",
			form: "长柄武器",
			daily_req: "狮牙斗士",
			champ_attrib_req: "混沌",
			world_mon_req: "史莱姆",
		},
		匣里灭辰: {
			star: "4",
			form: "长柄武器",
			daily_req: "雾海云间",
			champ_attrib_req: "雾虚",
			world_mon_req: "绘卷",
		},
		决斗之枪: {
			star: "4",
			form: "长柄武器",
			daily_req: "凛风奔狼",
			champ_attrib_req: "地脉",
			world_mon_req: "花蜜",
		},
		黑岩刺枪: {
			star: "4",
			form: "长柄武器",
			daily_req: "雾海云间",
			champ_attrib_req: "雾虚",
			world_mon_req: "徽记",
		},
		贯虹之槊: {
			star: "5",
			form: "长柄武器",
			daily_req: "漆黑陨铁",
			champ_attrib_req: "骨片",
			world_mon_req: "鸦印",
		},
		雪葬的星银: {
			star: "4",
			form: "双手剑",
			daily_req: "高塔孤王",
			champ_attrib_req: "号角",
			world_mon_req: "史莱姆",
		},
		龙脊长枪: {
			star: "4",
			form: "长柄武器",
			daily_req: "凛风奔狼",
			champ_attrib_req: "雾虚",
			world_mon_req: "徽记",
		},
		忍冬之果: {
			star: "4",
			form: "法器",
			daily_req: "狮牙斗士",
			champ_attrib_req: "混沌",
			world_mon_req: "花蜜",
		},
	},
};
